services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KQttP-WhRynRWA-sp_8uvRSKqTizFMn3fawrWOfmYfoCyujYoAkSQvsHP7DxnvjyvYU
      POSTGRES_DB: hawkeye
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
  api:
    build:
      context: ./HawkeyeServer.Api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
