create table if not exists users (
    id bigint primary key generated by default as identity,
    email text not null unique,
    name text,
    picture text,
    created_at timestamp without time zone default now()
);
