create table if not exists users (
    id bigint primary key generated by default as identity,
    email text not null unique,
    name text,
    picture text,
    created_at timestamp default now()
);

create table if not exists trip (
    id bigint primary key generated by default as identity,
    title text not null,
    destination text not null,
    start_date date not null,
    end_date date not null,
    join_code char(10) not null unique,
    created_at timestamp default now(),
    created_by bigint not null references users(id) on delete cascade
);

create table if not exists place (
    id bigint primary key generated by default as identity,
    name text not null,
    longitude double precision not null,
    latitude double precision not null,
    date date not null,
    trip_id bigint not null references trip(id) on delete cascade
);

create table if not exists activity (
    id bigint primary key generated by default as identity,
    name text not null,
    start_time time without time zone not null,
    place_id bigint not null references place(id) on delete cascade
);

create table if not exists trip_mate (
    trip_id bigint not null references trip(id) on delete cascade,
    user_id bigint not null references users(id) on delete cascade,
    added_at timestamp default now(),
    primary key (trip_id, user_id)
);
