create table if not exists users (
    id bigint primary key generated by default as identity,
    email text not null unique,
    name text,
    picture text,
    created_at timestamp without time zone default now()
);

create table if not exists trip (
    id bigint primary key generated by default as identity,
    title text not null,
    destination text not null,
    start_date date not null,
    end_date date not null,
    created_at timestamp without time zone default now()
);
