name: CI/CD Pipeline

on:
  push:
    branches: [ prod ]

jobs:
  build:
    name: Build and Deploy to VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v3.14.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Create SSH Key File
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Ensure app directory exists on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} \
          "mkdir -p ${{ secrets.APP_DIRECTORY }}"

      - name: Copy Files to VM
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
            --exclude 'pgdata' \
            ./ ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:${{ secrets.APP_DIRECTORY }}

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd ${{ secrets.APP_DIRECTORY }}
            docker compose down
            docker compose up --build -d
          EOF
